# Generated by Django 5.2.16 on 2026-08-04 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvenementJournal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Identifiant technique')),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le')),
                ('cree_par_systeme', models.CharField(blank=True, help_text="Nom du processus/système automatisé à l'origine de la création.", max_length=150, verbose_name='Créé par (système)')),
                ('modifie_le', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modifié le')),
                ('modifie_par_systeme', models.CharField(blank=True, max_length=150, verbose_name='Modifié par (système)')),
                ('version', models.PositiveIntegerField(default=1, help_text='Compteur entier incrémenté à chaque modification, pour détecter les écritures concurrentes.', verbose_name='Version')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('archive', 'Archivé'), ('cloture', 'Clôturé')], db_index=True, default='actif', max_length=30, verbose_name='Statut du cycle de vie')),
                ('origine_donnee', models.CharField(choices=[('saisie_manuelle', 'Saisie manuelle'), ('importee', 'Importée'), ('synchronisee', 'Synchronisée depuis un autre système'), ('generee_auto', 'Générée automatiquement')], default='saisie_manuelle', max_length=30, verbose_name='Origine de la donnée')),
                ('motif_derniere_modification', models.TextField(blank=True, help_text='Texte libre, obligatoire dès qu’il ne s’agit pas d’une création.', verbose_name='Motif de la dernière modification')),
                ('supprime_le', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('entite_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Identifiant de l’entité référencée')),
                ('systeme_source', models.CharField(blank=True, help_text="Label souple du système fonctionnel à l'origine de la référence.", max_length=100, verbose_name='Système source')),
                ('action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('publication', 'Publication'), ('moderation', 'Modération'), ('connexion', 'Connexion'), ('autre', 'Autre')], max_length=30, verbose_name='Action')),
                ('cible_libelle', models.CharField(blank=True, max_length=255, verbose_name='Cible (libellé)')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Détails')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Laisser vide et renseigner « Créé par (système) » si l'action est automatisée/synchronisée.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('entite_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype', verbose_name='Type d’entité référencée')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modifies', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_supprimes', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
            ],
            options={
                'verbose_name': 'Événement de journal',
                'verbose_name_plural': 'Événements de journal',
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['action'], name='journal_eve_action_f8e83c_idx'), models.Index(fields=['entite_type', 'entite_id'], name='journal_eve_entite__32f54b_idx')],
            },
        ),
    ]
