# Generated by Django 5.2.16 on 2026-08-14 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("journal", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evenementjournal",
            name="cree_par",
            field=models.ForeignKey(
                blank=True,
                help_text="Laisser vide et renseigner « Créé par (système) » si l'action est automatisée/synchronisée.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_crees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AddField(
            model_name="evenementjournal",
            name="entite_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="contenttypes.contenttype",
                verbose_name="Type d’entité référencée",
            ),
        ),
        migrations.AddField(
            model_name="evenementjournal",
            name="modifie_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_modifies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifié par",
            ),
        ),
        migrations.AddField(
            model_name="evenementjournal",
            name="supprime_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_supprimes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Supprimé par",
            ),
        ),
        migrations.AddIndex(
            model_name="evenementjournal",
            index=models.Index(fields=["action"], name="journal_eve_action_f8e83c_idx"),
        ),
        migrations.AddIndex(
            model_name="evenementjournal",
            index=models.Index(
                fields=["entite_type", "entite_id"],
                name="journal_eve_entite__32f54b_idx",
            ),
        ),
    ]
