# Generated by Django 5.2.16 on 2026-09-08 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='badges',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_role_36d76d_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='etablissement',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
    ]
