# Generated by Django 5.2.16 on 2026-08-04 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('referentiels', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('icone', models.CharField(default='🏅', help_text='Emoji ou code icône court.', max_length=10, verbose_name='Icône')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='referentiels.etablissement', verbose_name='Établissement'),
        ),
        migrations.AddField(
            model_name='user',
            name='organisation',
            field=models.ForeignKey(blank=True, help_text='Renseigné si le compte représente/gère une organisation publiante.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='referentiels.organisation', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('etudiant', 'Étudiant'), ('moderateur', 'Modérateur'), ('administrateur', 'Administrateur'), ('organisation', 'Organisation')], db_index=True, default='etudiant', max_length=20, verbose_name='Rôle'),
        ),
        migrations.AddField(
            model_name='user',
            name='badges',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs', to='users.badge', verbose_name='Badges'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_user_role_36d76d_idx'),
        ),
    ]
