# Generated by Django 5.2.16 on 2026-08-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Commentaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant technique",
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Créé le"
                    ),
                ),
                (
                    "cree_par_systeme",
                    models.CharField(
                        blank=True,
                        help_text="Nom du processus/système automatisé à l'origine de la création.",
                        max_length=150,
                        verbose_name="Créé par (système)",
                    ),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Modifié le"
                    ),
                ),
                (
                    "modifie_par_systeme",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Modifié par (système)"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Compteur entier incrémenté à chaque modification, pour détecter les écritures concurrentes.",
                        verbose_name="Version",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("suspendu", "Suspendu"),
                            ("archive", "Archivé"),
                            ("cloture", "Clôturé"),
                        ],
                        db_index=True,
                        default="actif",
                        max_length=30,
                        verbose_name="Statut du cycle de vie",
                    ),
                ),
                (
                    "origine_donnee",
                    models.CharField(
                        choices=[
                            ("saisie_manuelle", "Saisie manuelle"),
                            ("importee", "Importée"),
                            ("synchronisee", "Synchronisée depuis un autre système"),
                            ("generee_auto", "Générée automatiquement"),
                        ],
                        default="saisie_manuelle",
                        max_length=30,
                        verbose_name="Origine de la donnée",
                    ),
                ),
                (
                    "motif_derniere_modification",
                    models.TextField(
                        blank=True,
                        help_text="Texte libre, obligatoire dès qu’il ne s’agit pas d’une création.",
                        verbose_name="Motif de la dernière modification",
                    ),
                ),
                (
                    "supprime_le",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Supprimé le"
                    ),
                ),
                (
                    "type_contenu",
                    models.CharField(
                        choices=[("texte", "Texte"), ("audio", "Audio")],
                        default="texte",
                        max_length=10,
                        verbose_name="Type de contenu",
                    ),
                ),
                ("contenu", models.TextField(blank=True, verbose_name="Contenu")),
                (
                    "audio_fichier",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="commentaires/audio/",
                        verbose_name="Fichier audio",
                    ),
                ),
                (
                    "audio_duration",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Durée audio (secondes)"
                    ),
                ),
                (
                    "est_epingle",
                    models.BooleanField(default=False, verbose_name="Épinglé"),
                ),
                (
                    "est_reponse_acceptee",
                    models.BooleanField(default=False, verbose_name="Réponse acceptée"),
                ),
            ],
            options={
                "verbose_name": "Commentaire",
                "verbose_name_plural": "Commentaires",
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="MediaJointCommentaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("gif", "GIF"),
                            ("audio", "Audio"),
                            ("video", "Vidéo"),
                            ("document", "Document"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="commentaires/medias/",
                        verbose_name="Fichier",
                    ),
                ),
                (
                    "url_externe",
                    models.URLField(blank=True, verbose_name="URL externe"),
                ),
            ],
            options={
                "verbose_name": "Média joint (commentaire)",
                "verbose_name_plural": "Médias joints (commentaires)",
            },
        ),
        migrations.CreateModel(
            name="ReactionCommentaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_reaction",
                    models.CharField(max_length=30, verbose_name="Type de réaction"),
                ),
                (
                    "cree_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
            ],
            options={
                "verbose_name": "Réaction (commentaire)",
                "verbose_name_plural": "Réactions (commentaires)",
            },
        ),
        migrations.CreateModel(
            name="VoteCommentaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("up", "Positif"), ("down", "Négatif")],
                        max_length=10,
                        verbose_name="Direction",
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
            ],
            options={
                "verbose_name": "Vote (commentaire)",
                "verbose_name_plural": "Votes (commentaires)",
            },
        ),
    ]
