# Generated by Django 5.2.16 on 2026-08-14 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commentaires", "0001_initial"),
        ("news", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="commentaire",
            name="auteur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commentaires_publies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Auteur",
            ),
        ),
        migrations.AddField(
            model_name="commentaire",
            name="cree_par",
            field=models.ForeignKey(
                blank=True,
                help_text="Laisser vide et renseigner « Créé par (système) » si l'action est automatisée/synchronisée.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_crees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AddField(
            model_name="commentaire",
            name="mentions",
            field=models.ManyToManyField(
                blank=True,
                related_name="commentaires_mentionne",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Mentions",
            ),
        ),
        migrations.AddField(
            model_name="commentaire",
            name="modifie_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_modifies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifié par",
            ),
        ),
        migrations.AddField(
            model_name="commentaire",
            name="news",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commentaires",
                to="news.news",
                verbose_name="News",
            ),
        ),
        migrations.AddField(
            model_name="commentaire",
            name="reponse_a",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reponses",
                to="commentaires.commentaire",
                verbose_name="En réponse à",
            ),
        ),
        migrations.AddField(
            model_name="commentaire",
            name="supprime_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_supprimes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Supprimé par",
            ),
        ),
        migrations.AddField(
            model_name="mediajointcommentaire",
            name="commentaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medias",
                to="commentaires.commentaire",
                verbose_name="Commentaire",
            ),
        ),
        migrations.AddField(
            model_name="reactioncommentaire",
            name="commentaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="commentaires.commentaire",
                verbose_name="Commentaire",
            ),
        ),
        migrations.AddField(
            model_name="reactioncommentaire",
            name="utilisateur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions_commentaires",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="votecommentaire",
            name="commentaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="commentaires.commentaire",
                verbose_name="Commentaire",
            ),
        ),
        migrations.AddField(
            model_name="votecommentaire",
            name="utilisateur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes_commentaires",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddIndex(
            model_name="commentaire",
            index=models.Index(
                fields=["news", "est_epingle"], name="commentaire_news_id_561b29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commentaire",
            index=models.Index(
                fields=["reponse_a"], name="commentaire_reponse_56b30e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="reactioncommentaire",
            constraint=models.UniqueConstraint(
                fields=("commentaire", "utilisateur", "type_reaction"),
                name="reaction_commentaire_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="votecommentaire",
            constraint=models.UniqueConstraint(
                fields=("commentaire", "utilisateur"),
                name="vote_commentaire_unique_par_utilisateur",
            ),
        ),
    ]
