# Generated by Django 5.2.16 on 2026-09-01 19:49

import common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentaires', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='audio_fichier',
            field=models.FileField(blank=True, null=True, storage=common.storage.get_raw_media_storage, upload_to='commentaires/audio/', verbose_name='Fichier audio'),
        ),
        migrations.AlterField(
            model_name='mediajointcommentaire',
            name='fichier',
            field=models.FileField(blank=True, null=True, storage=common.storage.get_raw_media_storage, upload_to='commentaires/medias/', verbose_name='Fichier'),
        ),
    ]
