# Generated by Django 5.2.16 on 2026-08-04 23:23

import django.db.models.deletion
import liens.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LienPublication',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Identifiant technique')),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le')),
                ('cree_par_systeme', models.CharField(blank=True, help_text="Nom du processus/système automatisé à l'origine de la création.", max_length=150, verbose_name='Créé par (système)')),
                ('modifie_le', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modifié le')),
                ('modifie_par_systeme', models.CharField(blank=True, max_length=150, verbose_name='Modifié par (système)')),
                ('version', models.PositiveIntegerField(default=1, help_text='Compteur entier incrémenté à chaque modification, pour détecter les écritures concurrentes.', verbose_name='Version')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('archive', 'Archivé'), ('cloture', 'Clôturé')], db_index=True, default='actif', max_length=30, verbose_name='Statut du cycle de vie')),
                ('origine_donnee', models.CharField(choices=[('saisie_manuelle', 'Saisie manuelle'), ('importee', 'Importée'), ('synchronisee', 'Synchronisée depuis un autre système'), ('generee_auto', 'Générée automatiquement')], default='saisie_manuelle', max_length=30, verbose_name='Origine de la donnée')),
                ('motif_derniere_modification', models.TextField(blank=True, help_text='Texte libre, obligatoire dès qu’il ne s’agit pas d’une création.', verbose_name='Motif de la dernière modification')),
                ('supprime_le', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('url_publique', models.URLField(max_length=500, verbose_name='URL publique')),
                ('code_court', models.CharField(default=liens.models._generer_code_court, max_length=20, unique=True, verbose_name='Code court')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='liens/qrcodes/', verbose_name='QR code')),
                ('visibilite', models.CharField(choices=[('public', 'Public'), ('prive', 'Privé'), ('limite', 'Limité')], default='public', max_length=20, verbose_name='Visibilité')),
                ('mot_de_passe_hash', models.CharField(blank=True, max_length=255, verbose_name='Mot de passe (haché)')),
                ('expiration', models.DateTimeField(blank=True, null=True, verbose_name='Expiration')),
                ('usage_unique', models.BooleanField(default=False, verbose_name='Usage unique')),
                ('deja_utilise', models.BooleanField(default=False, editable=False, verbose_name='Déjà utilisé')),
                ('scope_etablissement', models.CharField(blank=True, max_length=200, verbose_name='Établissement (portée)')),
                ('scope_province', models.CharField(blank=True, max_length=100, verbose_name='Province (portée)')),
                ('scope_promotion', models.CharField(blank=True, max_length=100, verbose_name='Promotion (portée)')),
                ('scope_organisation', models.CharField(blank=True, max_length=200, verbose_name='Organisation (portée)')),
                ('scope_classe', models.CharField(blank=True, max_length=100, verbose_name='Classe (portée)')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Laisser vide et renseigner « Créé par (système) » si l'action est automatisée/synchronisée.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modifies', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_publication', to='news.news', verbose_name='News')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_supprimes', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
            ],
            options={
                'verbose_name': 'Lien de publication',
                'verbose_name_plural': 'Liens de publication',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='LienAcces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_acces', models.CharField(choices=[('clic', 'Clic'), ('scan', 'Scan QR')], max_length=10, verbose_name="Type d'accès")),
                ('horodatage', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Horodatage')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('lien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces', to='liens.lienpublication', verbose_name='Lien')),
            ],
            options={
                'verbose_name': 'Accès à un lien',
                'verbose_name_plural': 'Accès aux liens',
                'indexes': [models.Index(fields=['lien', 'type_acces'], name='liens_liena_lien_id_9653d5_idx')],
            },
        ),
    ]
