# Generated by Django 5.2.16 on 2026-08-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentJoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255, verbose_name="Nom")),
                (
                    "fichier",
                    models.FileField(
                        upload_to="news/documents/", verbose_name="Fichier"
                    ),
                ),
                (
                    "taille",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Taille (octets)"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Type MIME"
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
            ],
            options={
                "verbose_name": "Document joint",
                "verbose_name_plural": "Documents joints",
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant technique",
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Créé le"
                    ),
                ),
                (
                    "cree_par_systeme",
                    models.CharField(
                        blank=True,
                        help_text="Nom du processus/système automatisé à l'origine de la création.",
                        max_length=150,
                        verbose_name="Créé par (système)",
                    ),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Modifié le"
                    ),
                ),
                (
                    "modifie_par_systeme",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Modifié par (système)"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Compteur entier incrémenté à chaque modification, pour détecter les écritures concurrentes.",
                        verbose_name="Version",
                    ),
                ),
                (
                    "origine_donnee",
                    models.CharField(
                        choices=[
                            ("saisie_manuelle", "Saisie manuelle"),
                            ("importee", "Importée"),
                            ("synchronisee", "Synchronisée depuis un autre système"),
                            ("generee_auto", "Générée automatiquement"),
                        ],
                        default="saisie_manuelle",
                        max_length=30,
                        verbose_name="Origine de la donnée",
                    ),
                ),
                (
                    "motif_derniere_modification",
                    models.TextField(
                        blank=True,
                        help_text="Texte libre, obligatoire dès qu’il ne s’agit pas d’une création.",
                        verbose_name="Motif de la dernière modification",
                    ),
                ),
                (
                    "supprime_le",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Supprimé le"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("publie", "Publié"),
                            ("archive", "Archivé"),
                            ("signale", "Signalé"),
                        ],
                        db_index=True,
                        default="brouillon",
                        max_length=30,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("projet", "Projet"),
                            ("evenement", "Événement"),
                            ("annonce", "Annonce"),
                            ("sondage", "Sondage"),
                            ("consultation", "Consultation"),
                            ("petition", "Pétition"),
                            ("information", "Information"),
                            ("reforme", "Réforme"),
                            ("idee", "Idée"),
                            ("conference", "Conférence"),
                            ("reunion", "Réunion"),
                            ("atelier", "Atelier"),
                            ("appel_participation", "Appel à participation"),
                            ("article", "Article"),
                            ("publication", "Publication"),
                            ("actualite", "Actualité"),
                        ],
                        default="information",
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                ("titre", models.CharField(max_length=255, verbose_name="Titre")),
                ("description", models.TextField(verbose_name="Description")),
                ("contenu", models.TextField(blank=True, verbose_name="Contenu")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="news/couvertures/",
                        verbose_name="Image de couverture",
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Estuaire", "Estuaire"),
                            ("Haut-Ogooué", "Haut-Ogooué"),
                            ("Moyen-Ogooué", "Moyen-Ogooué"),
                            ("Ngounié", "Ngounié"),
                            ("Nyanga", "Nyanga"),
                            ("Ogooué-Ivindo", "Ogooué-Ivindo"),
                            ("Ogooué-Lolo", "Ogooué-Lolo"),
                            ("Ogooué-Maritime", "Ogooué-Maritime"),
                            ("Woleu-Ntem", "Woleu-Ntem"),
                        ],
                        max_length=30,
                        verbose_name="Province",
                    ),
                ),
                (
                    "lieu",
                    models.CharField(blank=True, max_length=255, verbose_name="Lieu"),
                ),
                (
                    "date_debut",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de début"
                    ),
                ),
                (
                    "date_fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de fin"
                    ),
                ),
                (
                    "visibilite",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("prive", "Privé"),
                            ("limite", "Limité"),
                        ],
                        default="public",
                        max_length=20,
                        verbose_name="Visibilité",
                    ),
                ),
                (
                    "partages",
                    models.PositiveIntegerField(default=0, verbose_name="Partages"),
                ),
            ],
            options={
                "verbose_name": "News",
                "verbose_name_plural": "News",
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="NewsImageGalerie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="news/galerie/", verbose_name="Image"),
                ),
                (
                    "legende",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Légende"
                    ),
                ),
                (
                    "ordre",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordre"),
                ),
            ],
            options={
                "verbose_name": "Image de galerie",
                "verbose_name_plural": "Images de galerie",
                "ordering": ["ordre"],
            },
        ),
        migrations.CreateModel(
            name="NewsMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Vidéo"),
                            ("youtube", "YouTube"),
                            ("audio", "Audio"),
                            ("document", "Document"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="news/medias/",
                        verbose_name="Fichier",
                    ),
                ),
                (
                    "url_externe",
                    models.URLField(
                        blank=True,
                        help_text="Pour les médias hébergés ailleurs (ex: YouTube).",
                        verbose_name="URL externe",
                    ),
                ),
                (
                    "vignette",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="news/medias/vignettes/",
                        verbose_name="Vignette",
                    ),
                ),
                ("titre", models.CharField(max_length=255, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "duree",
                    models.CharField(
                        blank=True,
                        help_text="Format libre, ex: '3:45'.",
                        max_length=20,
                        verbose_name="Durée",
                    ),
                ),
                (
                    "ordre",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordre"),
                ),
                (
                    "cree_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
            ],
            options={
                "verbose_name": "Média (News)",
                "verbose_name_plural": "Médias (News)",
                "ordering": ["ordre", "cree_le"],
            },
        ),
        migrations.CreateModel(
            name="NewsVue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "horodatage",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Horodatage"
                    ),
                ),
                (
                    "adresse_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vue de News",
                "verbose_name_plural": "Vues de News",
            },
        ),
        migrations.CreateModel(
            name="ReactionNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_reaction",
                    models.CharField(
                        choices=[
                            ("coeur", "Cœur"),
                            ("jaime", "J'aime"),
                            ("bravo", "Bravo"),
                            ("youpi", "Youpi"),
                            ("wow", "Wow"),
                            ("jaimepas", "Je n'aime pas"),
                        ],
                        max_length=20,
                        verbose_name="Type de réaction",
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
            ],
            options={
                "verbose_name": "Réaction (News)",
                "verbose_name_plural": "Réactions (News)",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=50, unique=True, verbose_name="Nom"),
                ),
            ],
            options={
                "verbose_name": "Étiquette",
                "verbose_name_plural": "Étiquettes",
                "ordering": ["nom"],
            },
        ),
    ]
