# Generated by Django 5.2.16 on 2026-08-05 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("news", "0001_initial"),
        ("referentiels", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="auteur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="news_publiees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Auteur",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="categorie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="news",
                to="referentiels.categorie",
                verbose_name="Catégorie",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="cree_par",
            field=models.ForeignKey(
                blank=True,
                help_text="Laisser vide et renseigner « Créé par (système) » si l'action est automatisée/synchronisée.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_crees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="etablissement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="news",
                to="referentiels.etablissement",
                verbose_name="Établissement",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="modifie_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_modifies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifié par",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="news",
                to="referentiels.organisation",
                verbose_name="Organisation",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="supprime_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_supprimes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Supprimé par",
            ),
        ),
        migrations.AddField(
            model_name="documentjoint",
            name="news",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="news.news",
                verbose_name="News",
            ),
        ),
        migrations.AddField(
            model_name="newsimagegalerie",
            name="news",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="galerie",
                to="news.news",
                verbose_name="News",
            ),
        ),
        migrations.AddField(
            model_name="newsmedia",
            name="news",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medias",
                to="news.news",
                verbose_name="News",
            ),
        ),
        migrations.AddField(
            model_name="newsvue",
            name="news",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vues",
                to="news.news",
                verbose_name="News",
            ),
        ),
        migrations.AddField(
            model_name="newsvue",
            name="utilisateur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="reactionnews",
            name="news",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="news.news",
                verbose_name="News",
            ),
        ),
        migrations.AddField(
            model_name="reactionnews",
            name="utilisateur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions_news",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="news",
                to="news.tag",
                verbose_name="Étiquettes",
            ),
        ),
        migrations.AddIndex(
            model_name="newsvue",
            index=models.Index(
                fields=["news", "horodatage"], name="news_newsvu_news_id_c5aa9e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="reactionnews",
            constraint=models.UniqueConstraint(
                fields=("news", "utilisateur"),
                name="reaction_unique_par_utilisateur_news",
            ),
        ),
        migrations.AddIndex(
            model_name="news",
            index=models.Index(
                fields=["statut", "visibilite"], name="news_news_statut_dafe4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="news",
            index=models.Index(fields=["type"], name="news_news_type_5e04e9_idx"),
        ),
        migrations.AddIndex(
            model_name="news",
            index=models.Index(
                fields=["province"], name="news_news_provinc_f5b00a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="news",
            index=models.Index(fields=["slug"], name="news_news_slug_915ecd_idx"),
        ),
    ]
