# Generated by Django 5.2.16 on 2026-08-29 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_restaurer_reaction_unique_par_utilisateur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reactionnews',
            name='reaction_unique_par_utilisateur_news',
        ),
        migrations.AlterField(
            model_name='reactionnews',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions_news', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
