# Generated by Django 5.2.16 on 2026-09-01 19:49

import common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_reactions_libres_sans_contrainte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentjoint',
            name='fichier',
            field=models.FileField(storage=common.storage.get_raw_media_storage, upload_to='news/documents/', verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='newsmedia',
            name='fichier',
            field=models.FileField(blank=True, null=True, storage=common.storage.get_raw_media_storage, upload_to='news/medias/', verbose_name='Fichier'),
        ),
    ]
