# Generated by Django 5.2.16 on 2026-09-08 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentiels', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('icone', models.CharField(default='🏅', help_text='Emoji ou code icône court.', max_length=10, verbose_name='Icône')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MembreTenant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Identifiant technique')),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le')),
                ('cree_par_systeme', models.CharField(blank=True, help_text="Nom du processus/système automatisé à l'origine de la création.", max_length=150, verbose_name='Créé par (système)')),
                ('modifie_le', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modifié le')),
                ('modifie_par_systeme', models.CharField(blank=True, max_length=150, verbose_name='Modifié par (système)')),
                ('version', models.PositiveIntegerField(default=1, help_text='Compteur entier incrémenté à chaque modification, pour détecter les écritures concurrentes.', verbose_name='Version')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('archive', 'Archivé'), ('cloture', 'Clôturé')], db_index=True, default='actif', max_length=30, verbose_name='Statut du cycle de vie')),
                ('origine_donnee', models.CharField(choices=[('saisie_manuelle', 'Saisie manuelle'), ('importee', 'Importée'), ('synchronisee', 'Synchronisée depuis un autre système'), ('generee_auto', 'Générée automatiquement')], default='saisie_manuelle', max_length=30, verbose_name='Origine de la donnée')),
                ('motif_derniere_modification', models.TextField(blank=True, help_text='Texte libre, obligatoire dès qu’il ne s’agit pas d’une création.', verbose_name='Motif de la dernière modification')),
                ('supprime_le', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('user_id', models.PositiveBigIntegerField(db_index=True, help_text='Référence users.User.id dans le schéma public -- volontairement pas une ForeignKey (isolation inter-schémas, voir TokenManager.user_id).', verbose_name='Utilisateur (identifiant global)')),
                ('role', models.CharField(choices=[('etudiant', 'Étudiant'), ('moderateur', 'Modérateur'), ('administrateur', 'Administrateur'), ('organisation', 'Organisation')], db_index=True, default='etudiant', max_length=20, verbose_name='Rôle')),
                ('statut_adhesion', models.CharField(choices=[('en_attente', "En attente d'approbation"), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('suspendue', 'Suspendue')], db_index=True, default='acceptee', max_length=20, verbose_name="Statut de l'adhésion")),
                ('demande_le', models.DateTimeField(auto_now_add=True, verbose_name='Demandé le')),
                ('traitee_le', models.DateTimeField(blank=True, null=True, verbose_name='Traitée le')),
                ('traitee_par_id', models.PositiveBigIntegerField(blank=True, help_text='users.User.id (public) du membre ayant accepté/refusé la demande -- même principe que user_id.', null=True, verbose_name='Traitée par (identifiant global)')),
                ('motif_refus', models.TextField(blank=True, verbose_name='Motif de refus')),
                ('badges', models.ManyToManyField(blank=True, related_name='membres', to='adhesions.badge', verbose_name='Badges')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Laisser vide et renseigner « Créé par (système) » si l'action est automatisée/synchronisée.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('etablissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='referentiels.etablissement', verbose_name='Établissement')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modifies', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('organisation', models.ForeignKey(blank=True, help_text='Renseigné si ce membre représente/gère une organisation publiante dans ce tenant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='referentiels.organisation', verbose_name='Organisation')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_supprimes', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
            ],
            options={
                'verbose_name': 'Membre du tenant',
                'verbose_name_plural': 'Membres du tenant',
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['user_id'], name='adhesions_m_user_id_870f6f_idx'), models.Index(fields=['role'], name='adhesions_m_role_210bd6_idx'), models.Index(fields=['statut_adhesion'], name='adhesions_m_statut__9591c6_idx')],
                'constraints': [models.UniqueConstraint(fields=('user_id',), name='adhesions_membretenant_unique_user')],
            },
        ),
    ]
