# Generated by Django 5.2.16 on 2026-08-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TokenSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "access_token_lifetime",
                    models.IntegerField(
                        default=5, help_text="Durée de vie du token d'accès en minutes"
                    ),
                ),
                (
                    "refresh_token_lifetime",
                    models.IntegerField(
                        default=1440,
                        help_text="Durée de vie du token de rafraîchissement en minutes",
                    ),
                ),
                (
                    "max_tokens_per_user",
                    models.IntegerField(
                        default=5,
                        help_text="Nombre maximum de tokens actifs par utilisateur",
                    ),
                ),
                (
                    "rotate_refresh_tokens",
                    models.BooleanField(
                        default=True,
                        help_text="Générer un nouveau token de rafraîchissement à chaque utilisation",
                    ),
                ),
                (
                    "blacklist_after_rotation",
                    models.BooleanField(
                        default=True,
                        help_text="Mettre en liste noire les anciens tokens après rotation",
                    ),
                ),
                (
                    "cookie_secure",
                    models.BooleanField(
                        default=True, help_text="Cookies uniquement en HTTPS"
                    ),
                ),
                (
                    "cookie_samesite",
                    models.CharField(
                        choices=[
                            ("Lax", "Lax"),
                            ("Strict", "Strict"),
                            ("None", "None"),
                        ],
                        default="Lax",
                        max_length=10,
                    ),
                ),
                (
                    "cookie_domain",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "enable_blacklist",
                    models.BooleanField(
                        default=True, help_text="Activer la liste noire des tokens"
                    ),
                ),
                (
                    "blacklist_cleanup_after",
                    models.IntegerField(
                        default=60, help_text="Nettoyer la liste noire après X minutes"
                    ),
                ),
                (
                    "require_https",
                    models.BooleanField(
                        default=True, help_text="Exiger HTTPS pour les tokens"
                    ),
                ),
                (
                    "validate_ip",
                    models.BooleanField(
                        default=True, help_text="Valider l'IP de l'utilisateur"
                    ),
                ),
                (
                    "validate_user_agent",
                    models.BooleanField(
                        default=True, help_text="Valider le User-Agent"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuration de token",
                "verbose_name_plural": "Configurations de tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TokenManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("username", models.CharField(max_length=255)),
                ("tenant_id", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_revoked", models.BooleanField(default=False)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("device_id", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "device_family",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "device_brand",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "device_model",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "Mobile"),
                            ("tablet", "Tablet"),
                            ("desktop", "Desktop"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("os_family", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "browser_family",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("last_used", models.DateTimeField(auto_now=True)),
                ("access_token", models.TextField(blank=True, null=True)),
                ("refresh_token", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "token_manager",
                "indexes": [
                    models.Index(
                        fields=["user_id", "tenant_id"],
                        name="token_manag_user_id_fb8027_idx",
                    ),
                    models.Index(
                        fields=["device_id"], name="token_manag_device__f562e1_idx"
                    ),
                    models.Index(
                        fields=["is_revoked"], name="token_manag_is_revo_5ca1c4_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="token_manag_expires_93ae56_idx"
                    ),
                ],
            },
        ),
    ]
