# Generated by Django 5.2.16 on 2026-08-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant technique",
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Créé le"
                    ),
                ),
                (
                    "cree_par_systeme",
                    models.CharField(
                        blank=True,
                        help_text="Nom du processus/système automatisé à l'origine de la création.",
                        max_length=150,
                        verbose_name="Créé par (système)",
                    ),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Modifié le"
                    ),
                ),
                (
                    "modifie_par_systeme",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Modifié par (système)"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Compteur entier incrémenté à chaque modification, pour détecter les écritures concurrentes.",
                        verbose_name="Version",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("suspendu", "Suspendu"),
                            ("archive", "Archivé"),
                            ("cloture", "Clôturé"),
                        ],
                        db_index=True,
                        default="actif",
                        max_length=30,
                        verbose_name="Statut du cycle de vie",
                    ),
                ),
                (
                    "origine_donnee",
                    models.CharField(
                        choices=[
                            ("saisie_manuelle", "Saisie manuelle"),
                            ("importee", "Importée"),
                            ("synchronisee", "Synchronisée depuis un autre système"),
                            ("generee_auto", "Générée automatiquement"),
                        ],
                        default="saisie_manuelle",
                        max_length=30,
                        verbose_name="Origine de la donnée",
                    ),
                ),
                (
                    "motif_derniere_modification",
                    models.TextField(
                        blank=True,
                        help_text="Texte libre, obligatoire dès qu’il ne s’agit pas d’une création.",
                        verbose_name="Motif de la dernière modification",
                    ),
                ),
                (
                    "supprime_le",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Supprimé le"
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, unique=True, verbose_name="Nom"),
                ),
                (
                    "couleur",
                    models.CharField(
                        default="#5B4DFF",
                        help_text="Couleur hexadécimale utilisée pour les badges/étiquettes côté frontend.",
                        max_length=20,
                        verbose_name="Couleur",
                    ),
                ),
                (
                    "icone",
                    models.CharField(
                        default="Newspaper",
                        help_text="Nom d'icône du set EGEN utilisé côté frontend.",
                        max_length=50,
                        verbose_name="Icône",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Etablissement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant technique",
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Créé le"
                    ),
                ),
                (
                    "cree_par_systeme",
                    models.CharField(
                        blank=True,
                        help_text="Nom du processus/système automatisé à l'origine de la création.",
                        max_length=150,
                        verbose_name="Créé par (système)",
                    ),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Modifié le"
                    ),
                ),
                (
                    "modifie_par_systeme",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Modifié par (système)"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Compteur entier incrémenté à chaque modification, pour détecter les écritures concurrentes.",
                        verbose_name="Version",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("suspendu", "Suspendu"),
                            ("archive", "Archivé"),
                            ("cloture", "Clôturé"),
                        ],
                        db_index=True,
                        default="actif",
                        max_length=30,
                        verbose_name="Statut du cycle de vie",
                    ),
                ),
                (
                    "origine_donnee",
                    models.CharField(
                        choices=[
                            ("saisie_manuelle", "Saisie manuelle"),
                            ("importee", "Importée"),
                            ("synchronisee", "Synchronisée depuis un autre système"),
                            ("generee_auto", "Générée automatiquement"),
                        ],
                        default="saisie_manuelle",
                        max_length=30,
                        verbose_name="Origine de la donnée",
                    ),
                ),
                (
                    "motif_derniere_modification",
                    models.TextField(
                        blank=True,
                        help_text="Texte libre, obligatoire dès qu’il ne s’agit pas d’une création.",
                        verbose_name="Motif de la dernière modification",
                    ),
                ),
                (
                    "supprime_le",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Supprimé le"
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="Nom")),
                ("province", models.CharField(max_length=100, verbose_name="Province")),
            ],
            options={
                "verbose_name": "Établissement",
                "verbose_name_plural": "Établissements",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant technique",
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Créé le"
                    ),
                ),
                (
                    "cree_par_systeme",
                    models.CharField(
                        blank=True,
                        help_text="Nom du processus/système automatisé à l'origine de la création.",
                        max_length=150,
                        verbose_name="Créé par (système)",
                    ),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Modifié le"
                    ),
                ),
                (
                    "modifie_par_systeme",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Modifié par (système)"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Compteur entier incrémenté à chaque modification, pour détecter les écritures concurrentes.",
                        verbose_name="Version",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("suspendu", "Suspendu"),
                            ("archive", "Archivé"),
                            ("cloture", "Clôturé"),
                        ],
                        db_index=True,
                        default="actif",
                        max_length=30,
                        verbose_name="Statut du cycle de vie",
                    ),
                ),
                (
                    "origine_donnee",
                    models.CharField(
                        choices=[
                            ("saisie_manuelle", "Saisie manuelle"),
                            ("importee", "Importée"),
                            ("synchronisee", "Synchronisée depuis un autre système"),
                            ("generee_auto", "Générée automatiquement"),
                        ],
                        default="saisie_manuelle",
                        max_length=30,
                        verbose_name="Origine de la donnée",
                    ),
                ),
                (
                    "motif_derniere_modification",
                    models.TextField(
                        blank=True,
                        help_text="Texte libre, obligatoire dès qu’il ne s’agit pas d’une création.",
                        verbose_name="Motif de la dernière modification",
                    ),
                ),
                (
                    "supprime_le",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Supprimé le"
                    ),
                ),
                ("nom", models.CharField(max_length=150, verbose_name="Nom")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="organisations/logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("association_etudiante", "Association étudiante"),
                            ("administration", "Administration"),
                            ("club", "Club"),
                            ("departement", "Département académique"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Organisation",
                "verbose_name_plural": "Organisations",
                "ordering": ["nom"],
            },
        ),
    ]
