"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import re
from pathlib import Path
from datetime import timedelta


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-your-secret-key-here'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition
SHARED_APPS = (
    'django_tenants',
    'domain',
    'tenants',
    'token_manager',
    'django.contrib.contenttypes',
    # auth/admin/users sont volontairement AUSSI dans SHARED_APPS (en plus de
    # TENANT_APPS ci-dessous). django-tenants supporte explicitement ce
    # double-listage : chaque schéma (public ET chaque tenant) obtient alors
    # sa PROPRE table utilisateurs, isolée. C'est ce qui permet d'avoir :
    #   - un espace "admin global" (schéma public) avec ses super-admins de
    #     plateforme, qui gèrent les Tenants/Domains,
    #   - un espace "admin tenant" (schéma de l'établissement) avec ses
    #     propres admins/utilisateurs locaux, complètement isolés.
    # Sans ça, le schéma public n'a aucune table auth_user/users_user et il
    # est structurellement impossible de se connecter à un admin global.
    'django.contrib.auth',
    'django.contrib.admin',
    'users',
    'referentiels',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'rest_framwork_simplejwt.token_blacklist',
    # 'django_user_agents',
    'rest_framework',
    "django_filters",
    'drf_yasg',
    'corsheaders',
    "common",
)

TENANT_APPS = (
    'django.contrib.auth',
    'django.contrib.admin',

    # Niveau 0
    "users",

    # Niveau 1 — CIVITAS NEWS (domaines métier de contenu)
    "referentiels",
    "news",
    "commentaires",
    "sondages",
    "liens",
    "notifications",
    "journal",
    "moderation",
    "statistiques",
)

# Assure que django_tenants n'est pas dupliqué dans INSTALLED_APPS.
# Note : la déduplication ici ne concerne QUE le registre Python des apps.
# Le routage des migrations par schéma (public vs tenant) est piloté
# séparément par django-tenants à partir des tuples SHARED_APPS / TENANT_APPS
# ci-dessus, donc le double-listage d'auth/admin/users reste bien effectif.
INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

# Configuration de l'utilisateur personnalisé
AUTH_USER_MODEL = 'users.User'

# Configuration des modèles pour django-tenant
TENANT_DOMAIN_MODEL = 'domain.Domain'  # Chemin complet vers le modèle Domain
TENANT_MODEL = 'tenants.Tenant'  # Chemin complet vers le modèle Tenant

MIDDLEWARE = [
    # CorsMiddleware DOIT être avant tout middleware custom susceptible de
    # court-circuiter la requête (TenantMiddleware / TenantJWTMiddleware).
    # CorsMiddleware.__call__ intercepte lui-même les preflights OPTIONS
    # (méthode check_preflight) et répond 200 + headers CORS SANS jamais
    # appeler get_response() -- donc sans jamais atteindre TenantJWTMiddleware.
    # S'il est placé après, un preflight vers une route AUTHENTICATED se fait
    # rejeter en 401 par TenantJWTMiddleware avant même que CorsMiddleware ne
    # s'exécute : aucun header CORS n'est ajouté, et le navigateur bloque la
    # requête en l'affichant comme une erreur CORS (qui masque en réalité une
    # erreur 401). Voir https://github.com/adamchainz/django-cors-headers
    # ("CorsMiddleware should be placed as high as possible").
    'corsheaders.middleware.CorsMiddleware',
    'tenants.middleware.TenantMiddleware',  # Doit être en premier parmi les middlewares métier (résolution schéma tenant)
    'token_manager.middleware.TenantJWTMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'django_user_agents.middleware.UserAgentMiddleware',  # Laisser en commentaire si non prioritaire
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),  # Templates globaux du projet
        ],
        'APP_DIRS': True,  # Permet à Django de chercher les templates dans les dossiers templates de chaque app
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend',
        'NAME': 'db_educ',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'localhost',
        'PORT': '5436',
    }
}

LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)  # crée le dossier si inexistant

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'rotating_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'app.log',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',  # ← obligatoire pour les emojis
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        '': {  # logger racine
            'handlers': ['rotating_file', 'console'],
            'level': 'DEBUG',  # capture tout niveau
            'propagate': True,
        },
        'django': {
            'handlers': ['rotating_file'],
            'level': 'WARNING',  # log Django uniquement warnings+errors dans fichier
            'propagate': False,
        },
    },
}


# Database routing
DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)

# Configuration de l'authentification
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Configuration des sessions
SESSION_COOKIE_NAME = 'tenant_sessionid'
# None => Django utilise le hostname exact de la requête comme domaine de
# cookie. C'est volontaire ici : ça isole naturellement la session de
# l'admin global (localhost) de celle de chaque tenant (ecole1.localhost),
# sans configuration dynamique supplémentaire.
SESSION_COOKIE_DOMAIN = None
# CRITIQUE : ne JAMAIS forcer 'Secure' en dev/HTTP, sinon le navigateur
# n'enregistre jamais le cookie de session -> connexion admin impossible
# (le login "réussit" côté serveur mais on est renvoyé sur la page de
# connexion à chaque requête suivante, faute de session persistée).
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
# Idem pour le cookie CSRF, indispensable au formulaire de login admin.
CSRF_COOKIE_SECURE = not DEBUG

# Configuration de la sécurité
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Configuration des permissions
PERMISSIONS = {
    'can_manage_users': 'Can manage users',
    'can_view_reports': 'Can view reports',
    'can_manage_settings': 'Can manage settings',
}

# Internationalization
LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Media files (Uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configuration des fichiers statiques pour le développement
if DEBUG:
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static'),
    ]
else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Configuration du stockage des fichiers statiques
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Configuration de la taille maximale des fichiers uploadés
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB

# Configuration des types MIME autorisés
ALLOWED_EXTENSIONS = {
    'image': ['.jpg', '.jpeg', '.png', '.gif', '.bmp', '.webp'],
    'document': ['.pdf', '.doc', '.docx', '.xls', '.xlsx', '.txt'],
    'archive': ['.zip', '.rar', '.7z'],
}

# Configuration du stockage des fichiers
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_RENDERER_CLASSES': [
        'common.camel_case.CamelCaseJSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'common.camel_case.CamelCaseJSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser'
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/min' if DEBUG else '100/day',
        'user': '300/min' if DEBUG else '1000/day'
    }
}



# Configuration JWT
# Configuration JWT par défaut
# Ces paramètres peuvent être surchargés dynamiquement par token_manager/apps.py
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    'JTI_CLAIM': 'jti',
    'TOKEN_REFRESH_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenRefreshSerializer',
}

# Token Manager settings
TOKEN_MANAGER = {
    'MAX_TOKENS_PER_USER': 5,
    'TOKEN_BLACKLIST_ENABLED': True,
    'TOKEN_BLACKLIST_CLEANUP_AFTER': timedelta(days=7),
    'TOKEN_REFRESH_THRESHOLD': timedelta(minutes=5),
    'TOKEN_REUSE_DETECTION': True,
    'TOKEN_REUSE_WINDOW': timedelta(minutes=1),
}

# Security settings
SECURE_SSL_REDIRECT = not DEBUG
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'

# Domaine racine de la plateforme -- déplacé ici (avant CORS, qui en a
# besoin) depuis son emplacement plus bas dans ce fichier ("Multi-tenant
# settings"), où il reste aussi documenté/référencé pour le reste du
# système de tenants (tenants/middleware.py, domain/api/v1/services.py).
MAIN_DOMAIN = 'localhost'

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
# En plus de la liste exacte ci-dessus : accepte tout sous-domaine de
# MAIN_DOMAIN (n'importe quel tenant), avec ou sans port, http ou https.
# Indispensable pour la résolution dynamique du tenant depuis l'URL du
# frontend (voir config/fonction.py:resolve_request_hostname) : sans
# cette regex, seule l'origine exacte "localhost:3000" était autorisée
# -- le navigateur bloquait la requête AVANT même qu'elle atteigne
# Django dès que le frontend était ouvert sur un sous-domaine comme
# "civitas.localhost:3000".
CORS_ALLOWED_ORIGIN_REGEXES = [
    rf'^https?://([a-zA-Z0-9-]+\.)?{re.escape(MAIN_DOMAIN)}(:\d+)?$',
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-tenant-domain',
]

# Swagger settings
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Basic': {
            'type': 'basic'
        }
    },
    'USE_SESSION_AUTH': True,
    'JSON_EDITOR': True,
}

# Multi-tenant settings
TENANT_MODEL = 'tenants.Tenant'
TENANT_DOMAIN_MODEL = 'domain.Domain'

# URL de base du frontend CIVITAS NEWS (SPA Vite), utilisée pour construire
# les URLs publiques des liens de partage (liens/models.py) quand le
# frontend ne fournit pas explicitement `urlPublique`.
FRONTEND_BASE_URL = 'http://localhost:5173'

# Clé de chiffrement pour les mots de passe de base de données
ENCRYPTION_KEY = 'ozQujKHvSUZE11J-JDcCi1CgvnJ4x3aDJOdclCxxhHI='

# Google Sign-In (token_manager/api/v1/views.py:GoogleAuthView) — OAuth Client
# ID (type "Web application") créé dans Google Cloud Console. Doit être
# IDENTIQUE à celui utilisé côté frontend (VITE_GOOGLE_CLIENT_ID) : c'est
# l'audience vérifiée sur le id_token reçu, condition indispensable à la
# sécurité du flux (sans quoi un id_token valide pour N'IMPORTE QUELLE
# app Google serait accepté ici). Jamais de valeur par défaut en dur —
# tant que la variable d'environnement n'est pas définie, GoogleAuthView
# répond 503 plutôt que d'accepter des tokens sans vérifier l'audience.
GOOGLE_OAUTH_CLIENT_ID = os.environ.get('GOOGLE_OAUTH_CLIENT_ID', '')
