# Generated by Django 5.2.16 on 2026-08-05 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        max_length=253, unique=True, verbose_name="Domaine"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=True, verbose_name="Domaine principal"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Domaine",
                "verbose_name_plural": "Domaines",
                "ordering": ["domain"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_primary", True)),
                        fields=("tenant", "is_primary"),
                        name="unique_primary_domain_per_tenant",
                    )
                ],
            },
        ),
    ]
