# Generated by Django 5.2.16 on 2026-08-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Signalement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant technique",
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Créé le"
                    ),
                ),
                (
                    "cree_par_systeme",
                    models.CharField(
                        blank=True,
                        help_text="Nom du processus/système automatisé à l'origine de la création.",
                        max_length=150,
                        verbose_name="Créé par (système)",
                    ),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Modifié le"
                    ),
                ),
                (
                    "modifie_par_systeme",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Modifié par (système)"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Compteur entier incrémenté à chaque modification, pour détecter les écritures concurrentes.",
                        verbose_name="Version",
                    ),
                ),
                (
                    "origine_donnee",
                    models.CharField(
                        choices=[
                            ("saisie_manuelle", "Saisie manuelle"),
                            ("importee", "Importée"),
                            ("synchronisee", "Synchronisée depuis un autre système"),
                            ("generee_auto", "Générée automatiquement"),
                        ],
                        default="saisie_manuelle",
                        max_length=30,
                        verbose_name="Origine de la donnée",
                    ),
                ),
                (
                    "motif_derniere_modification",
                    models.TextField(
                        blank=True,
                        help_text="Texte libre, obligatoire dès qu’il ne s’agit pas d’une création.",
                        verbose_name="Motif de la dernière modification",
                    ),
                ),
                (
                    "supprime_le",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Supprimé le"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("traite", "Traité"),
                            ("rejete", "Rejeté"),
                        ],
                        db_index=True,
                        default="en_attente",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "type_contenu",
                    models.CharField(
                        choices=[
                            ("news", "News"),
                            ("commentaire", "Commentaire"),
                            ("utilisateur", "Utilisateur"),
                            ("sondage", "Sondage"),
                        ],
                        max_length=20,
                        verbose_name="Type de contenu",
                    ),
                ),
                (
                    "contenu_id",
                    models.CharField(
                        max_length=50, verbose_name="Identifiant du contenu"
                    ),
                ),
                (
                    "titre_ou_apercu",
                    models.CharField(max_length=255, verbose_name="Titre ou aperçu"),
                ),
                (
                    "motif",
                    models.CharField(
                        choices=[
                            ("spam", "Spam"),
                            ("propos_inappropries", "Propos inappropriés"),
                            ("desinformation", "Désinformation"),
                            ("harcelement", "Harcèlement"),
                            ("autre", "Autre"),
                        ],
                        max_length=30,
                        verbose_name="Motif",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Signalement",
                "verbose_name_plural": "Signalements",
                "ordering": ["-cree_le"],
            },
        ),
    ]
