# Generated by Django 5.2.16 on 2026-08-14 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("moderation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="signalement",
            name="auteur_signalement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signalements_emis",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Auteur du signalement",
            ),
        ),
        migrations.AddField(
            model_name="signalement",
            name="cree_par",
            field=models.ForeignKey(
                blank=True,
                help_text="Laisser vide et renseigner « Créé par (système) » si l'action est automatisée/synchronisée.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_crees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AddField(
            model_name="signalement",
            name="modifie_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_modifies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifié par",
            ),
        ),
        migrations.AddField(
            model_name="signalement",
            name="supprime_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_supprimes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Supprimé par",
            ),
        ),
        migrations.AddIndex(
            model_name="signalement",
            index=models.Index(fields=["statut"], name="moderation__statut_9aa69f_idx"),
        ),
        migrations.AddIndex(
            model_name="signalement",
            index=models.Index(
                fields=["type_contenu", "contenu_id"],
                name="moderation__type_co_d9a9ba_idx",
            ),
        ),
    ]
