# Generated by Django 5.2.16 on 2026-08-04 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sondage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Identifiant technique')),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le')),
                ('cree_par_systeme', models.CharField(blank=True, help_text="Nom du processus/système automatisé à l'origine de la création.", max_length=150, verbose_name='Créé par (système)')),
                ('modifie_le', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modifié le')),
                ('modifie_par_systeme', models.CharField(blank=True, max_length=150, verbose_name='Modifié par (système)')),
                ('version', models.PositiveIntegerField(default=1, help_text='Compteur entier incrémenté à chaque modification, pour détecter les écritures concurrentes.', verbose_name='Version')),
                ('origine_donnee', models.CharField(choices=[('saisie_manuelle', 'Saisie manuelle'), ('importee', 'Importée'), ('synchronisee', 'Synchronisée depuis un autre système'), ('generee_auto', 'Générée automatiquement')], default='saisie_manuelle', max_length=30, verbose_name='Origine de la donnée')),
                ('motif_derniere_modification', models.TextField(blank=True, help_text='Texte libre, obligatoire dès qu’il ne s’agit pas d’une création.', verbose_name='Motif de la dernière modification')),
                ('supprime_le', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('programme', 'Programmé'), ('termine', 'Terminé'), ('archive', 'Archivé')], db_index=True, default='actif', max_length=20, verbose_name='Statut')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('question', models.CharField(max_length=500, verbose_name='Question')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sondages/', verbose_name='Image')),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(verbose_name='Date de fin')),
                ('type_vote', models.CharField(choices=[('unique', 'Choix unique'), ('multiple', 'Choix multiple')], default='unique', max_length=10, verbose_name='Type de vote')),
                ('anonymat', models.BooleanField(default=True, verbose_name='Anonymat')),
                ('visibilite_resultat', models.CharField(choices=[('instantane', 'Instantané'), ('masque_jusqua_fin', "Masqué jusqu'à la fin")], default='instantane', max_length=25, verbose_name='Visibilité du résultat')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Laisser vide et renseigner « Créé par (système) » si l'action est automatisée/synchronisée.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modifies', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sondages', to='news.news', verbose_name='News')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_supprimes', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
            ],
            options={
                'verbose_name': 'Sondage',
                'verbose_name_plural': 'Sondages',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='ChoixSondage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sondages/choix/', verbose_name='Image')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('sondage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='sondages.sondage', verbose_name='Sondage')),
            ],
            options={
                'verbose_name': 'Choix de sondage',
                'verbose_name_plural': 'Choix de sondage',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='VoteSondage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('choix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='sondages.choixsondage', verbose_name='Choix')),
                ('sondage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='sondages.sondage', verbose_name='Sondage')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_sondages', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Vote (sondage)',
                'verbose_name_plural': 'Votes (sondages)',
                'constraints': [models.UniqueConstraint(fields=('choix', 'utilisateur'), name='vote_sondage_unique_par_choix_utilisateur')],
            },
        ),
    ]
