# Generated by Django 5.2.16 on 2026-08-17 10:05

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondages', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votesondage',
            options={'ordering': ['-cree_le'], 'verbose_name': 'Vote (sondage)', 'verbose_name_plural': 'Votes (sondages)'},
        ),
        migrations.AddField(
            model_name='choixsondage',
            name='cree_le',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 8, 17, 10, 5, 51, 689020, tzinfo=datetime.timezone.utc), verbose_name='Créé le'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='votesondage',
            index=models.Index(fields=['sondage', 'utilisateur'], name='sondages_vo_sondage_40c0aa_idx'),
        ),
    ]
