# Generated by Django 5.2.16 on 2026-08-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant technique",
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Créé le"
                    ),
                ),
                (
                    "cree_par_systeme",
                    models.CharField(
                        blank=True,
                        help_text="Nom du processus/système automatisé à l'origine de la création.",
                        max_length=150,
                        verbose_name="Créé par (système)",
                    ),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Modifié le"
                    ),
                ),
                (
                    "modifie_par_systeme",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Modifié par (système)"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Compteur entier incrémenté à chaque modification, pour détecter les écritures concurrentes.",
                        verbose_name="Version",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("suspendu", "Suspendu"),
                            ("archive", "Archivé"),
                            ("cloture", "Clôturé"),
                        ],
                        db_index=True,
                        default="actif",
                        max_length=30,
                        verbose_name="Statut du cycle de vie",
                    ),
                ),
                (
                    "origine_donnee",
                    models.CharField(
                        choices=[
                            ("saisie_manuelle", "Saisie manuelle"),
                            ("importee", "Importée"),
                            ("synchronisee", "Synchronisée depuis un autre système"),
                            ("generee_auto", "Générée automatiquement"),
                        ],
                        default="saisie_manuelle",
                        max_length=30,
                        verbose_name="Origine de la donnée",
                    ),
                ),
                (
                    "motif_derniere_modification",
                    models.TextField(
                        blank=True,
                        help_text="Texte libre, obligatoire dès qu’il ne s’agit pas d’une création.",
                        verbose_name="Motif de la dernière modification",
                    ),
                ),
                (
                    "supprime_le",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Supprimé le"
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("actualite", "Actualité"),
                            ("sondage", "Sondage"),
                            ("annonce", "Annonce"),
                            ("alerte", "Alerte"),
                            ("consultation", "Consultation"),
                            ("decision", "Décision"),
                            ("reforme", "Réforme"),
                            ("rapport", "Rapport"),
                        ],
                        max_length=20,
                        verbose_name="Format",
                    ),
                ),
                ("titre", models.CharField(max_length=255, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "categorie_nom",
                    models.CharField(max_length=100, verbose_name="Catégorie — nom"),
                ),
                (
                    "categorie_couleur",
                    models.CharField(
                        default="#5B4DFF",
                        max_length=20,
                        verbose_name="Catégorie — couleur",
                    ),
                ),
                (
                    "categorie_icone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Catégorie — icône"
                    ),
                ),
                (
                    "lien",
                    models.CharField(blank=True, max_length=500, verbose_name="Lien"),
                ),
                (
                    "lu",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Lu"
                    ),
                ),
                (
                    "tag",
                    models.CharField(blank=True, max_length=50, verbose_name="Tag"),
                ),
                ("urgente", models.BooleanField(default=False, verbose_name="Urgente")),
                (
                    "category_tab",
                    models.CharField(
                        choices=[
                            ("all", "Toutes"),
                            ("direct", "Direct"),
                            ("news", "News"),
                            ("sondages", "Sondages"),
                            ("alertes", "Alertes"),
                        ],
                        default="all",
                        max_length=20,
                        verbose_name="Onglet",
                    ),
                ),
                ("notice", models.TextField(blank=True, verbose_name="Note")),
                (
                    "actions",
                    models.JSONField(blank=True, default=list, verbose_name="Actions"),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-cree_le"],
            },
        ),
    ]
